# import the libraries

In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt

In [9]:
import pandas as pd

  # importing data set

In [10]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [11]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [13]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# taking care of missing data


In [14]:
from sklearn.impute import SimpleImputer # sklearn is a library from where we imported simpleimputer

In [12]:
imputer =  SimpleImputer(missing_values=np.nan, strategy='mean')#here imputer is an object of the class simpleImputer the missing values are replaced by mean

In [13]:
imputer.fit(x[:,1:3])# method used to connect the imputer object with features

SimpleImputer()

In [14]:
x[:,1:3] = imputer.transform(x[:,1:3])

In [15]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# ENCODING CATAGORICAL DATA

In [16]:
#as there is catagorical data in our data set so we have to encode it into numerical data (binary which have noo relation between them) , 
#so the amchine could understand. no relation between the features

In [17]:
# using one hut encoding 

#  encoding the independent variable

In [18]:
 from sklearn.compose import ColumnTransformer #importing column transformer form sklearn library to transform the column 

In [19]:
from sklearn.preprocessing import OneHotEncoder #using onehotencoder to encode the catagorical data 

In [20]:
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough' )#  ct means making an object in which calling the class coumntransform
# x,y,z where x is what transformation u will make y which technique is used and z means where to apply that technique on the dataset

In [21]:
x = np.array(ct.fit_transform(x))

In [22]:
print(x) # as you can se that france ,spain,germany are encoded into the binary form 
#so that there could b no relation between them

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [23]:
dataset.info

<bound method DataFrame.info of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [24]:
print(dataset.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [25]:
from sklearn.preprocessing import LabelEncoder # importing labelencoder to encode the dependent variable 

In [26]:
le=LabelEncoder()

In [27]:
y=le.fit_transform(y)# no numpy array is used

In [28]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# splitting the data into test and training set

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [31]:
x_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [32]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [33]:
y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [34]:
y_test

array([0, 1])

# feature scaling

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc = StandardScaler()

In [38]:
x_train[:, 3:]=sc.fit_transform(x_train[:, 3:])

In [39]:
x_test[:, 3:]=sc.fit_transform(x_test[:, 3:])

In [41]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [42]:
print(x_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
